[package]
name = "haribote_lang"
version = "1.2"
edition = "2018"
author = "tamaron"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[[bin]]
name = "hrb"
path = "src/main.rs"